Feature/ground removal
fs-feup/autonomous-systems pull request #242
Opened 2024-02-04 00:12 UTC by Davide64-dev

2024-02-05 09:49 UTC, marhcouto commented
Task linked: [CU-8693hqq1d First implementation of the ground removal](https://app.clickup.com/t/8693hqq1d)

2024-02-05 11:05 UTC, marhcouto requested changes
All code seems great for now. Some notes:
- There are not instructions for installation of pcl, not sure if you know that or if they are necessary, it failed to find the library on my PC
- Changed to draft because I though this was WIP, but correct it if I'm wrong
- Cpplint is not passing, check that out

2024-02-05 18:10 UTC, marhcouto commented on src/perception/src/ground_removal/ransac.cpp
> +    seg.setOptimizeCoefficients (true);
Add some comments indicating what is being defined in these lines very briefly

2024-02-05 18:14 UTC, marhcouto commented on src/perception/test/ransac_test.cpp
> +TEST_F(RANSACTest, Test10) {
Tests are enough to check functionality, I'll just leave the suggestion to change the name of the tests to something more alusive of the tests itself, but as it is already in the comments, I leave it to you

2024-02-05 18:15 UTC, marhcouto commented
Task linked: [CU-8693htmxn Improve ground removal implementation](https://app.clickup.com/t/8693htmxn)

2024-02-09 21:23 UTC, marhcouto requested changes
Review in ClickUp

2024-02-10 10:53 UTC, marhcouto approved these changes

2024-02-10 15:45 UTC, BrunoDias201907828 approved these changes

2024-02-10 17:41 UTC, merged