FSF-2598 - Ros 2 can
fs-feup/autonomous-systems pull request #263
Opened 2024-04-01 11:08 UTC by PedroRomao3

2024-04-02 22:37 UTC, marhcouto requested changes
Some changes to be made here but overall gj

2024-04-02 22:37 UTC, marhcouto commented on src/ros_can/src/node/node_ros_can.cpp
> +    // Prepare the steering message
Add RCLCPP_DEBUG log here

2024-04-05 16:24 UTC, marhcouto approved these changes

2024-04-09 16:49 UTC, PedromLBarros commented
✅

2024-04-09 16:58 UTC, merged