Feature/execution time
fs-feup/autonomous-systems pull request #269
Opened 2024-04-09 14:54 UTC by Davide64-dev

2024-04-14 13:04 UTC, marhcouto requested changes
Output format is alright too. However, on top of what was mentioned:
- There is a need to document a bit better each scenario. Either divide them into multiple steps and use comments or find some way to inform on what scenarios the poind clouds represent.
- Not regarding this PR but would be good to fix: run the formatter, there are many things off format
- Not regarding this PR: solve compiler warnings, there are a few of them
- Also, this task was meant to do this for all modules, not just perception

2024-04-14 13:04 UTC, marhcouto commented on src/perception/test/performance_test.cpp
> +        pcl::io::loadPCDFile<pcl::PointXYZI>(file_name, *pcl_cloud);
Test format is overall good but I think it would be good to better document this. Separate into steps clearly would help here

2024-04-14 13:04 UTC, marhcouto commented on src/perception/test/performance_test.cpp
> +class PerceptionPerformanceTest : public ::testing::Test {
Again, this class needs documentation too, even if light

2024-04-28 17:06 UTC, marhcouto requested changes

2024-04-28 17:06 UTC, marhcouto commented on src/loc_map/test/loc_map_performance_test.cpp
> +    ConeMap coneMap = createConeMap(i);
Humm, havia 10 pq era p fazer a média

2024-04-28 17:06 UTC, marhcouto commented on src/planning/test/tests.cpp
> +  std::vector<PathPoint> path = processTriangulations(filePath, "250points");
Testes de planning ainda estão múltiplos testes em vez de um como nos outros

2024-04-28 17:13 UTC, Davide64-dev commented on src/loc_map/test/loc_map_performance_test.cpp
> +    ConeMap coneMap = createConeMap(i);
Certo, o cálculo da média continua, só que não é nesse ciclo. Esse ciclo faz variar o coneMap. O Ciclo que faz a média está na linha 187

2024-04-28 17:13 UTC, Davide64-dev commented on src/planning/test/tests.cpp
> +  std::vector<PathPoint> path = processTriangulations(filePath, "250points");
Vou tratar disso

2024-05-01 16:05 UTC, lourenco31 approved these changes

2024-05-01 16:07 UTC, merged