FSF-2956 Feat/cone heuristic
fs-feup/autonomous-systems pull request #273
Opened 2024-04-14 01:01 UTC by Davide64-dev

2024-04-14 08:59 UTC, marhcouto requested changes
The part of the messages is in another PR?

2024-04-14 08:59 UTC, marhcouto commented on src/perception/src/cone_evaluator/distance_predict.cpp
> +    double n_points_prediction = 0.5 * vertical_component * horizontal_component;
This is the number of points you think you should be receiving? The only think that concerns me here is that I don't see any part of the equations above taking the shape of the cone into account

2024-04-14 08:59 UTC, marhcouto commented on src/perception/test/distance_validator_test.cpp
> +  ASSERT_LE(coneConfidence, 1.0);
These assertions are only checking for utter absurdities, shouldn't they be a little tighter?

2024-04-15 22:44 UTC, PedroRomao3 approved these changes
seems ok, besides previous notes

2024-04-16 10:32 UTC, marhcouto approved these changes

2024-04-21 16:16 UTC, marhcouto approved these changes

2024-04-21 16:22 UTC, merged