FSF-3720 begging of planing adapters
fs-feup/autonomous-systems pull request #294
Opened 2024-05-13 14:40 UTC by lourenco31

2024-05-18 14:10 UTC, marhcouto requested changes
Small changes requested

2024-05-18 14:10 UTC, marhcouto commented on src/planning/include/planning/planning.hpp
>    Adapter *adapter; /**< Adapter instance for external communication */
Change to shared ptr

2024-05-18 14:10 UTC, marhcouto commented on src/planning/src/adapter_planning/eufs.cpp
> +  RCLCPP_INFO(this->node->get_logger(), "Received cones from EUFS");
Probably not a good idea to keep this as info, very high frequency, will fill the terminal up

2024-05-18 14:10 UTC, marhcouto commented on src/planning/src/adapter_planning/pacsim.cpp
> +    auto timer = this->node->create_wall_timer(std::chrono::milliseconds(100),
Probably can reduce the milliseconds, the callbacks are usually faster

2024-05-18 14:10 UTC, marhcouto commented on src/planning/src/planning/planning.cpp
> +  RCLCPP_INFO(this->get_logger(), "Planning received %d cones", (int)msg.cone_array.size());
Again, INFO might be too high of a logging level for callbacks of high frequency

2024-05-20 12:32 UTC, andrelds11 commented on src/planning/launch/planning.launch.py
> +                default_value="1",
is 1 actually the default value?

2024-05-21 07:36 UTC, lourenco31 commented on src/planning/src/planning/planning.cpp
> +  if (!using_simulated_se_ || mode == "vehicle") {
It's all in the adapters

2024-05-21 20:16 UTC, marhcouto approved these changes
Issues are basically code quality, will be solved later due to urgency in testing

2024-05-21 20:18 UTC, merged