feat(sim_infr): created adapters for other simulators
fs-feup/autonomous-systems pull request #295
Opened 2024-05-14 21:45 UTC by Davide64-dev

2024-05-15 13:28 UTC, marhcouto requested changes
That and FSSIM does not have a LiDAR

2024-05-15 13:28 UTC, marhcouto commented on src/perception/include/adapter_perception/testlidar.hpp
>    void mission_state_callback(const std::string& msg);
Correct message type

2024-05-15 22:13 UTC, Davide64-dev commented
@marhcouto criei apenas um launch file porque acho que é o que faz sentido neste package, mas queria saber a tua opinião

2024-05-16 09:21 UTC, marhcouto requested changes
Just that small request, sorry about the hassle

2024-05-16 09:21 UTC, marhcouto commented on src/perception/launch/perception.launch.py
> +                default_value="test",
Podes só mudar o nome do adapter para vehicle? Parece me um nome mais passivel de manter coerencia com os outros packages e isso facilita depois os launch files gerais pq usam todos o mesmo argumento

2024-05-16 14:50 UTC, Davide64-dev commented
@marhcouto Done

2024-05-16 15:17 UTC, BrunoDias201907828 approved these changes

2024-05-16 21:14 UTC, marhcouto approved these changes

2024-05-16 22:35 UTC, merged