fix(perception): launch file refactoring
fs-feup/autonomous-systems pull request #301
Opened 2024-05-24 10:14 UTC by Davide64-dev

2024-06-07 15:28 UTC, marhcouto requested changes
Just the one point in the evaluator node, the changes kind of break state estimation. I had changed it to be ready for more advanced evaluation in the future, using confidence and cone_color. Can you adapt perception evaluation to use or ignore that?

2024-06-07 15:28 UTC, marhcouto commented on src/evaluator/evaluator/formats.py
> -                    cone_color_dictionary[cone.color],
This will kind of break other things in state estimation

2024-06-15 15:48 UTC, marhcouto approved these changes
Sorry, forgot to approve!

2024-06-16 15:42 UTC, PedroRomao3 approved these changes

2024-06-16 15:56 UTC, merged