FSF-3621 FSF-3963 Control Refactoring + documentation
fs-feup/autonomous-systems pull request #312
Opened 2024-05-31 14:45 UTC by yvesb04

2024-05-31 17:46 UTC, marhcouto requested changes
Documentação está aprovada, mas não percebi muito bem, porque meteste aqui metade das coisas da tarefa de refactoring? Also, controlo não passa testes, fix that

2024-05-31 17:46 UTC, marhcouto commented on src/control/README.md
> +colcon build --package-up-to control
Queres adicionar isto ao tutorial de ROS?

2024-06-10 15:31 UTC, marhcouto requested changes
Para além destes pormenores, o carro não anda no eufs. Parece-me ser alguma coisa no cálculo do lookahead point, porque ele vai sempre para um que está fora da margem e depois a scaled velocity não é bem calculada

2024-06-10 15:31 UTC, marhcouto commented on src/common_lib/include/common_lib/structures/pose.hpp
> +  double heading_;
O heading n é o mesmo que a orientation?

2024-06-10 15:31 UTC, marhcouto commented on src/control/src/point_solver/psolver.cpp
> +Position PointSolver::cg_2_rear_axis(Position cg, double heading, double dist_cg_2_rear_axis) const {
This should probably go to VD

2024-06-10 15:31 UTC, marhcouto commented on src/control/src/point_solver/psolver.cpp
> +Position PointSolver::cg_2_rear_axis(Position cg, double heading, double dist_cg_2_rear_axis) const {
In common_lib

2024-06-10 16:08 UTC, yvesb04 commented
> Para além destes pormenores, o carro não anda no eufs. Parece-me ser alguma coisa no cálculo do lookahead point, porque ele vai sempre para um que está fora da margem e depois a scaled velocity não é bem calculada

é exatamente isso que queria testar essa semana, estive algum tempo a fazer workarounds mas acabei por n dar commit a nada por não serem soluções muito boas.

2024-06-10 16:20 UTC, yvesb04 commented on src/common_lib/include/common_lib/structures/pose.hpp
> +  double heading_;
parece que sim, não tinha reparado nesse detalhe, a estrutura que usavamos antes tinha os 2

2024-06-10 17:07 UTC, yvesb04 commented
for some reason (i think i rebased at some point badly) i had divergent branches so i had to make a merge

2024-06-10 22:31 UTC, marhcouto approved these changes

2024-06-11 11:32 UTC, merged