Eval system - Export and Cloud Operation FSF-4061
fs-feup/autonomous-systems pull request #321
Opened 2024-06-20 16:47 UTC by BrunoDias201907828

At the moment, you are unable to run the send_cloud.py since you need an authetication file, still the evaluator should run  and export the metrics to csv files

2024-06-21 11:59 UTC, marhcouto requested changes
All seems good, just two more points:
- Include doxygen documentation strings in the functions, like the ones in Evaluator
- Sort the thing about the secret

2024-06-21 11:59 UTC, marhcouto commented on src/cloud_storage/README.md
> +```sh
Maybe include this in dependencies install

2024-06-23 21:45 UTC, marhcouto approved these changes
Seems all good to me!

2024-06-24 14:52 UTC, Davide64-dev approved these changes
✅. Just a small note

2024-06-24 14:52 UTC, Davide64-dev commented on src/cloud_storage/README.md
> + - **planning**: Reads time_exec measurements from unit tests of control.
Small error here **planning** -> control. Check this

2024-06-24 15:13 UTC, merged