FSF-3928 fix(planning): updated planning diagrams
fs-feup/autonomous-systems pull request #322
Opened 2024-06-23 02:14 UTC by lourenco31

2024-06-23 21:09 UTC, marhcouto requested changes
All the diagrams seem great, just the note left on the submodules

2024-06-23 21:09 UTC, marhcouto commented on ext/interfaces
These updates from submodules, they ought to not come in in a PR like this. Please remove these updates. Pacsim is to be kept in branch main, not master, as merged in one of the latest PRs. The changes from interfaces can be kept

2024-06-26 15:00 UTC, andrelds11 approved these changes

2024-06-27 12:04 UTC, marhcouto approved these changes

2024-06-28 10:08 UTC, merged