FSF-4515 Planning evaluation implementation
fs-feup/autonomous-systems pull request #340
Opened 2024-08-19 17:22 UTC by lourenco31

2024-08-25 13:22 UTC, Davide64-dev requested changes
The content is great. However, I think the logic of synchronization of the planning and mocker nodes must be on the evaluator class itself, as it does not depend on the logic of the environment it is running on. But what do you think?

2024-08-25 13:22 UTC, Davide64-dev commented on src/evaluator/evaluator/eufs_adapter.py
> +
I think this is not necessary as the planning output and the mocker node subscriptions don't need to be in the adapter

2024-08-25 13:22 UTC, Davide64-dev commented on src/evaluator/evaluator/fsds_adapter.py
> +        self._planning_time_sync_.registerCallback(self.planning_callback)
Same thing as EUFS adapter

2024-08-25 13:22 UTC, Davide64-dev commented on src/evaluator/evaluator/pacsim_adapter.py
> +
Same thing

2024-09-08 20:48 UTC, lourenco31 commented
> The content is great. However, I think the logic of synchronization of the planning and mocker nodes must be on the evaluator class itself, as it does not depend on the logic of the environment it is running on. But what do you think?

I did it this way to be coherent with the other nodes and because the callback (self.planning_callback) varies according to the environment, but if there's a solution to the callback problem and you don't mind the different synchronization methods, I'll change it

2024-09-09 10:42 UTC, Davide64-dev commented
> > The content is great. However, I think the logic of synchronization of the planning and mocker nodes must be on the evaluator class itself, as it does not depend on the logic of the environment it is running on. But what do you think?
> 
> I did it this way to be coherent with the other nodes and because the callback (self.planning_callback) varies according to the environment, but if there's a solution to the callback problem and you don't mind the different synchronization methods, I'll change it

I think you can change it because the callback logic of the evaluator is already in the evaluator node class. So, I think we might have a repetition.

2024-09-16 13:06 UTC, Davide64-dev approved these changes

2024-09-18 11:51 UTC, merged