Large cone identification + testing
fs-feup/autonomous-systems pull request #363
Opened 2024-11-15 22:15 UTC by Flopes55

Large cone identification was added inside height validation and cylinder validation so perception can identify and differentiate large cones with no added complexity. The testing of this functions was altered to accommodate the changes made.  More information on the development tab for perception in Notion.

2024-11-28 17:15 UTC, yvesb04 commented
is foi fechado e ainda n levou merge? precisava disto para deteção de meta

2024-11-28 17:24 UTC, Davide64-dev commented
O PR vai ser alterado para a target branch ser a dev e não a main

2024-11-28 17:35 UTC, yvesb04 requested changes

2024-11-28 22:37 UTC, Flopes55 commented on src/perception/launch/vehicle.launch.py
> +                default_value="0.4",
max_height was at 0.4m before and a small cone's height is 0.325m so I kept the small cone height and added a treshold for large cones too (their height is 0.505m), this values still need testing using the recently recorded rosbags with large cones in them.

2024-12-01 15:53 UTC, Davide64-dev commented
@Flopes55 overall good just validate this please

2024-12-08 18:17 UTC, Davide64-dev approved these changes

2024-12-09 09:18 UTC, BrunoDias201907828 approved these changes

2024-12-09 12:27 UTC, merged