FSF-6569 | Set confidence to cones with cone evaluator + tests
fs-feup/autonomous-systems pull request #375
Opened 2024-12-31 16:43 UTC by Flopes55

Distance predict was removed and cone evaluator was added to manage all validators, associating a weight to every value they return. The validators now return multiple values in a vector for better precision. A cluster is evaluated in a 0 to 1 scale and a minimum confidence was set up so only cones with confidence above that value are considered cones. (A minimum cap was added to some validators to more heavily punish clusters) 

All weigths, caps and minimum confidence levels are in the launchfiles.

2025-01-08 15:31 UTC, BrunoDias201907828 requested changes
The weights do not need to be within [0,1] you can give higher values and just convert them so that they stay between that interval.

Using Scale by Sum: "x_i' = x_i / sum(x_j)"

Using Softmax: x_i' = exp(x_i) / sum(exp(x_j))

The Softmax enhances higher values and diminishes the impact of lower values. If you want to keep its proportion use the Scale by Sum

2025-01-11 18:13 UTC, Davide64-dev approved these changes

2025-01-13 10:56 UTC, BrunoDias201907828 approved these changes

2025-01-15 16:48 UTC, Davide64-dev approved these changes

2025-01-15 16:49 UTC, merged

2025-01-23 14:08 UTC, yvesb04 commented on src/perception/include/perception/parameters_factory.hpp
> +    pair.second /= weight_sum;
@Flopes55 @Davide64-dev Boas eu sei que isto já foi fechado mas não entendo porque isto é um unordered_map em vez de uma estrutura ou class normal, as keys são conhecidas e constantes, estas operações todas fariam mais sentido no construtor de uma classe. Se houver outra razão que perdi pfv digam-me pq isto está a criar conflitos com outro pull request. Eu posso fazer as alterações